baseURL: "https://bhat-meghana.github.io/" 
title: Meghana Bhat
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Education
          url: education/
          weight: 3 
        - name: Teaching
          url: teaching/
          weight: 4
        - name: Visits
          url: visits/
          weight: 5  
        # - name: Academics
        #   url: courses/
        #   weight: 4
        - name: Miscellaneous
          url: miscellaneous/
          weight: 6
          children:  # This defines the sub-pages under Miscellaneous
            - name: Links
              url: miscellaneous/links/  # You can adjust the URL as needed
              weight: 1
            - name: Photo Album
              url: miscellaneous/musings/  # You can adjust the URL as needed
              weight: 2

params:
    description: "I'm a PhD student in Mathematics at the Indian Institute of Technology Dharwad.
                  My research interest is in Commutative algebra. In particular, 
                  I work on problems related to Hilbert functions."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Meghana Bhat
          subtitle: "I'm a PhD student in Mathematics at the <a href='https://www.iitdh.ac.in' style='color: navy;'>Indian Institute of Technology Dharwad</a>. 
                     My research interest is in <i style='color: navy;'>Commutative algebra and Algebraic Geometry</i>. In particular, I work on problems related to <i style='color: navy;'>Hilbert functions</i>, and <i style='color: navy;'>Waring rank of forms</i>.
                    <br>
                    <br>
                    I am grateful to my thesis advisor is <a href='https://www.iitdh.ac.in/user-profile/shreedevi-masuti' style='color: navy;'>Prof. Shreedevi Masuti</a> for introducing me this area of research and for her guidance. Since November 2022, I am a Prime Minister's Research Fellow. Funding from PMRF has been instrumental in my research journey.
                    I am also a SPARC visiting research student at the Politecnico Di Torino, Italy, under the mentorship of <a href='https://www.polito.it/personale?p=enrico.carlini' style='color: navy;'>Prof. Enrico Carlini</a>.
                    <br>
                    <br>
                    Contact: mbhat.math@gmail.com, ma21dpf01@iitdh.ac.in
                    <br>
                    Office: 603, A2 Science Block, IIT Dharwad"
          imageUrl: "profile_picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Meghana Bhat
          buttons:
            - name: Research
              url: research/
            - name: Education
              url: education/ 
            - name: Teaching
              url: teaching/
            - name: Visits
              url: visits/   
            # - name: Academics
            #   url: courses/
            - name: Miscellaneous
              url: miscellaneous/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: CV
          url: /20250501.pdf
        - name: Email
          url: mailto:mbhat.math@gmail.com
        # - name: GitHub
        #   url: https://github.com/MeghanaBht
        - name: LinkedIn
          url: https://www.linkedin.com/in/meghanamath

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Meghana Bhat"
      icon: faviconM.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
