baseURL: "https://meghanabhat.github.io/" 
title: Meghana Bhat
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Education
          url: education/
          weight: 3 
        - name: Teaching
          url: teaching/
          weight: 4
        - name: Visits
          url: visits/
          weight: 5  
        # - name: Academics
        #   url: courses/
        #   weight: 4
        - name: Links
          url: links/
          weight: 6


params:
    description: "I'm a PhD student in Mathematics at the Indian Institute of Technology Dharwad.
                  My research interest is in Commutative algebra. In particular, 
                  I work on problems related to Hilbert functions."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Meghana Bhat
          subtitle: "I'm a PhD student in Mathematics at the Indian Institute of Technology Dharwad. 
                    My research interest is in Commutative algebra. In particular, 
                    I work on problems related to Hilbert functions.
                    <br> 
                    <br>
                    Contact: mbhat.math@gmail.com
                    <br>
                    Office: 530, A2 Science Block, IIT Dharwad"
          imageUrl: "profile_picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Meghana Bhat
          buttons:
            - name: Papers
              url: papers/
            - name: Education
              url: education/ 
            - name: Teaching
              url: teaching/
            - name: Visits
              url: visits/   
            # - name: Academics
            #   url: courses/
            - name: Links
              url: links/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: CV
          url: https://www.dropbox.com/scl/fi/q7f9awo81bi4ojvpo0hrn/CV_Meghana.pdf?rlkey=hcs081uuwipuikz8z8uqlvbug&dl=0
        - name: Email
          url: mailto:mbhat.math@gmail.com
        # - name: GitHub
        #   url: https://github.com/MeghanaBht
        - name: LinkedIn
          url: https://www.linkedin.com/in/meghanamath
           

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Meghana Bhat"
      icon: faviconM.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
